name: Check code style with Prettier

on:
  pull_request:
    branches: [ master ]

jobs:
  check-code-style:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install prettier
    - uses: borales/actions-yarn@v2.0.0
      with:
          cmd: global add prettier

    - name: Check code style with Prettier
      run: cd $GITHUB_WORKSPACE && prettier --check "{backend,frontend,types}/src/**/*{ts,tsx,js,jsx,css}"
